jobs:
  - name: jobvmanifest4
    type: manifest
    steps:
      - GET: resourcevtest-image4
      - GET: resourcevtest-ecsparam1
      
  - name: jobvmanifest5
    type: manifest
    steps:
      - GET: resourcevtest-image5
      - GET: resourcevtest-ecsparam1
      - GET: resourcevtest-dockeroption1
      - GET: resourcevtest-replica1
      - GET: jobvmanifest4
      
  - name: jobvecsdeploy2
    type: escDeploy
    steps:
      - GET: jobvmanifest5
      - GET: resourcevtest-ecscluster2
