jobs:
  - name: jobvmanifest1
    type: manifest
    steps:
      - GET: resourcevtest-image3
      - GET: resourcevtest-dockeroption1
      - GET: resourcevtest-param1
      
  - name: jobvmanifest2
    type: manifest
    steps:
      - GET: resourcevtest-replica2
      - GET: resourcevtest-image3
      - GET: resourcevtest-dockeroption2
      
  - name: jobvmanifest2
    type: manifest
    steps:
      - GET: resourcevtest-replica2
      - GET: resourcevtest-param2
      - GET: resourcevtest-image4
      - GET: resourcevtest-image4
      - GET: resourcevtest-dockeroption2
