jobs:
  - name: jobvmanifest4
    type: manifest
    steps:
      - GET: resourcevtest-image3
      - GET: resourcev-ecsparam
      
  - name: jobvmanifest5
    type: manifest
    steps:
      - GET: resourcevtest-image4
      - GET: resourcev-ecsparam
      - GET: jobvmanifest4
      
  #- name: jobvecsdeploy2
   # type: escDeploy
   # steps:
    #  - GET: jobvmanifest5
    #  - GET: resourcevtest-ecscluster2
