jobs:
  - name: vanmanifest6064
    type: manifest
    steps:
      - GET: van-image6064
      - GET: van-replica6064
      
  - name: vanecsdeploy6064
    type: ecsDeploy
    steps:
      - GET: vanmanifest6064
      - GET: van-ecscluster6064
      
