jobs:
  - name: task5job-manifest6064a
    type: manifest
    steps:
      - GET: task5-image6064
      - GET: task5-dockeroption6064
     # - GET: task5-param6064a
      - GET: task5-replica6064
      
  - name: task5job-ecsdeploy6064
    type: ecsDeploy
    steps:
      - GET: task5job-manifest6064
      - GET: test6064-ecscluster11
      
  - name: task5job-manifest6064b
    type: manifest
    steps:
      - GET: task5job-manifest6064a
