jobs:
  - name: jobvmanifest1
    type: manifest
    steps:
      - GET: resourcevtest-image1
      - GET: resourcevtest-image2
      #- PUT: resourcevtest-image2
      
  - name: jobvmanifest2
    type: manifest
    steps:
      - PUT: resourcevtest-image1
      - GET: resourcev-image
