jobs:
  - name: van-manifest6064a
    type: manifest
    steps:
      - GET: task5-image6064a
      - GET: task5-dockeroption6064a
      
  - name: van-ecsdeploy6064a
    type: ecsDeploy
    steps:
      - GET: task5job-manifest6064a
      - GET: task5-ecscluster6064
      
